In [2]:
import numpy as np

In [3]:
n1=np.random.normal(100,1,(5,5))#np.random.normal(loc,scale,size)loc正态分布均值 scale标准差 size矩阵大小
n1

array([[ 99.61605673,  99.31860946,  99.57887763, 100.53518554,
        100.35103082],
       [ 98.34302127,  99.91013498,  99.27835836,  98.86024952,
         99.89666146],
       [100.5014159 , 100.82427414, 102.07967629, 100.64070122,
        100.47138551],
       [100.3463732 ,  98.89621458,  99.18585897,  99.75632647,
        100.78375927],
       [ 99.4794749 , 100.33615707, 101.25271808,  99.49284103,
        100.28674428]])

In [8]:
n2=np.random.randint(0,10,(5,5))
n2

array([[5, 8, 4, 5, 6],
       [5, 9, 4, 1, 0],
       [7, 1, 0, 5, 7],
       [0, 0, 5, 3, 5],
       [8, 2, 0, 8, 2]])

In [10]:
np.concatenate((n2,n2),axis=0)#axis=1合并行 concatenate级联

array([[5, 8, 4, 5, 6],
       [5, 9, 4, 1, 0],
       [7, 1, 0, 5, 7],
       [0, 0, 5, 3, 5],
       [8, 2, 0, 8, 2],
       [5, 8, 4, 5, 6],
       [5, 9, 4, 1, 0],
       [7, 1, 0, 5, 7],
       [0, 0, 5, 3, 5],
       [8, 2, 0, 8, 2]])

In [11]:
#np.hstack和np.vstack水平和竖直级联

In [21]:
n3=np.random.randint(0,150,(5,7))
n3

array([[ 94, 122, 122,  19,  61,  63, 102],
       [  6,  40,  51, 138,  95,   4,  52],
       [ 62, 136, 100,  86,  64, 145,  56],
       [ 26, 145, 141,  77,  34,  23,  45],
       [144,  69, 120,  70,  31,  52,  20]])

In [22]:
n4=np.split(n3,(1,3))# hsplit和vsplit切分列和行
n4

[array([[ 94, 122, 122,  19,  61,  63, 102]]),
 array([[  6,  40,  51, 138,  95,   4,  52],
        [ 62, 136, 100,  86,  64, 145,  56]]),
 array([[ 26, 145, 141,  77,  34,  23,  45],
        [144,  69, 120,  70,  31,  52,  20]])]

In [23]:
n5=np.vsplit(n3,(1,3))
n5

[array([[ 94, 122, 122,  19,  61,  63, 102]]),
 array([[  6,  40,  51, 138,  95,   4,  52],
        [ 62, 136, 100,  86,  64, 145,  56]]),
 array([[ 26, 145, 141,  77,  34,  23,  45],
        [144,  69, 120,  70,  31,  52,  20]])]